version: "3.9"
name: project

services:
  nginx:
    container_name: nginx_${PROJECT_NAME}
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
    links:
      - php
      - db
    networks:
      - default

  php:
    container_name: php_${PROJECT_NAME}
    build: php
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log
    links:
      - db
      - redis
    networks:
      - default

  db:
    container_name: postgres_${PROJECT_NAME}
    image: postgres:latest
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_default:/var/lib/mysql:rw
    ports:
      - "5432:5432"
    networks:
      - default

  redis:
    container_name: redis_${PROJECT_NAME}
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper_${PROJECT_NAME}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - kafka_network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_${PROJECT_NAME}
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui_${PROJECT_NAME}
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    ports:
      - '8080:8080'
    depends_on:
      - kafka
    networks:
      - kafka_network

volumes:
  db_default:

networks:
  default:
  kafka_network:
    driver: bridge
